# Set update schedule for GitHub Actions

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every day
      interval: daily
      time: "13:02"
      timezone: Europe/Athens


  - package-ecosystem: "gomod"
    directory: "/GeorgiPalaviq/"
    schedule:
      # Check for updates to GitHub Actions every day
      interval: daily
      time: "11:25"
      timezone: Europe/Athens
    commit-message:
      prefix: "[GeorgiPalaviq]"

  - package-ecosystem: "gomod"
    directory: "/GeorgiStefanov/"
    schedule:
      # Check for updates to GitHub Actions every day
      interval: daily
      time: "11:25"
      timezone: Europe/Athens
    commit-message:
      prefix: "[GeorgiStefanov]"