# Set update schedule for GitHub Actions

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every day
      interval: daily
      time: "14:30"
      timezone: Europe/Athens

  - package-ecosystem: "gomod"
    directory: "/GeorgiPalaviq"
    schedule:
      # Check for updates to GitHub Actions every day
      interval: daily
      time: "16:33"
      timezone: Europe/Athens
    commit-message:
      prefix: "[skip ci][GeorgiPalaviq]"

  - package-ecosystem: "gomod"
    directory: "/GeorgiStefanov/"
    schedule:
      # Check for updates to GitHub Actions every day
      interval: daily
      time: "16:33"
      timezone: Europe/Athens
    commit-message:
      prefix: "[skip ci][GeorgiStefanov]"