# Set update schedule for GitHub Actions

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every day
      interval: daily
      time: "13:50"
      timezone: Europe/Athens

  - package-ecosystem: gomod
    directory: "/Georgi**"
    schedule:
      interval: daily
      time: "13:50"
      timezone: Europe/Athens
