# Set update schedule for GitHub Actions

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every day
      interval: daily
      time: "14:40"
      timezone: Europe/Athens

      #das; kjmaslkj hlfhgb asjhgshsdahdsa day: 
    # dfjkhaskjh as