name: Build Workflow

on:
  workflow_call:
    inputs:
      docker_image_name:
        description: 'Name of the Docker image'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test
        run: echo "Build is running on ${{ github.run_id }} for ${{ github.repository }} with image ${{ github.event.inputs.docker_image_name }}"