name: comment_test

on:
  issue_comment:
    types: [created]
  
# some change

jobs:
  dump:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:

    - name: $github
      run: echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
