name: PR-testing

on:
  push:
  

env:
  ME: test-test-1
  VCPKG_ROOT: '/usr/local/share/vcpkg'

jobs:
  check:
    name: PR-testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Open PR
        id: open_pr
        uses: rematocorp/open-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          from-branch: test-test-1
          to-branch: main
          repository-owner: pko-pako
          repository: Tech-Exercises

      - name: Echo mergeable PR number
        if: always()
        run: echo ${{ steps.open_pr.outputs.pull_number }}