name: PR-testing

on:
  push:
  

env:
  ME: test-test-1
  VCPKG_ROOT: '/usr/local/share/vcpkg'

jobs:
  create-pr-on-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@4
    
    - name: Create pull request
      uses: thomaseizinger/create-pull-request@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        head: ${{ github.ref }}
        base: main
        title: "An automatically created PR!"
        run: echo ${{ steps.open_pr.outputs.pull_number }}