name: Create Pull Request

on:
  workflow_dispatch:
  push:
    

env:
  GH_TOKEN: ${{ secrets.PR_RIGHTS_GITHUB_TOKEN}}
  PR_BODY: updating-version
  PR_TITLE: updating-version

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create a new branch
        run: git checkout -b automated-branch

      - name: Try commiting something
        run: |
            echo "tosho" > ./tosho.txt
            git config --global user.email "github-actions@example.com"
            git config --global user.name "GitHub Actions"
            git add .
            git commit -m "Automated changes"
            git push --set-upstream origin automated-branch

      - name: Create Pull Request
        run: gh pr create --title $PR_TITLE --body $PR_BODY --base main --head ${GITHUB_REF##*/}
