name: Create Pull Request

on:
  push:
    branches:
      - pr-creating-test
  workflow_dispatch:
  schedule:
  - cron: '0 2 * * 1'
  
env:
  GH_TOKEN: ${{ secrets.PR_RIGHTS_GITHUB_TOKEN }} # this token has to have repo, workflow and org:read permissions
  PR_TITLE: "Sync with Upstream"
  PR_BODY: "This pull request syncs our fork with the latest changes from microsoft/vcpkg."
  BASE_BRANCH: "master"  # Specify the base branch for syncing
  PUBLIC_REPOSITORY: "https://github.com/microsoft/vcpkg.git" # Original repository

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create Pull Request
        run: |
          PR_POST_BODY="{
            \"title\": \"${{PR_TITLE}}\",
            \"body\": \"${{PR_BODY}}\",
            \"head\": \"upstream_sync_branch\",
            \"base\": \"${{env.PUBLIC_REPOSITORY}}\"
          }"
          curl -X POST \
            -H "Authorization: token ${{ env.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "$PR_POST_BODY" \
            "https://api.github.com/repos/pko-pako/Tech-Exercises/pulls"
