name: Create Pull Request

on:
  push:

env:
  GH_TOKEN: ${{ secrets.PR_RIGHTS_GITHUB_TOKEN}}

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        run: gh pr create --title "Your pull request title" --body "Your pull request description" --base main --head test-test-1
