name: Create Pull Request

on:
  workflow_dispatch:
  push:
    

env:
  GH_TOKEN: ${{ secrets.PR_RIGHTS_GITHUB_TOKEN}}
  PR_BODY: updating-version
  PR_TITLE: updating-version

permissions: write-all

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PR_RIGHTS_GITHUB_TOKEN }}
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "title"
          body: "body"
          base: "syncing"
          branch: "main"
        env:
          GITHUB_TOKEN: ${{ secrets.PR_RIGHTS_GITHUB_TOKEN }}

