name: Create Pull Request

on:
  push:

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PR_RIGHTS_GITHUB_TOKEN }}
          branch: main
