name: Create Pull Request

on:
  workflow_dispatch:
    

env:
  GH_TOKEN: ${{ secrets.PR_RIGHTS_GITHUB_TOKEN}}
  PR_BODY: updating-version
  PR_TITLE: updating-version

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Try commiting something
        run: |
            echo "tosho" > ./tosho.txt
            git add .
            git commit -m "Automated changes"

      - name: Create Pull Request
        run: gh pr create --title $PR_TITLE --body $PR_BODY --base main --head ${GITHUB_REF##*/}
