name: My Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 2 * * *' # every night at 2:00 AM

env:
  IMAGE_NAME: "NAME:DATE"

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      docker_image_name: NAME:DATE
