name: My Workflow

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
    IMAGE_NAME: "NAME:DATE"

jobs:

    build:
        uses: ./.github/workflows/build.yml
        with:
            docker_image_name: ${{ env.IMAGE_NAME}}

    integration-test:
        if: ${{ github.event_name == 'schedule' }}
        needs: build
        uses: ./.github/workflows/test.yml
        with:
            docker_image_name: ${{env.IMAGE_NAME}}
