name: Integration Test Workflow

on:
    # schedule:
    #     - cron: '0 2 * * *' # every night at 2:00 AM
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
  IMAGE_NAME: "NAME:DATE"

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
    - name: Build
      uses: ./.github/workflows/build.yml
      with:
        docker_image_name: ${{ env.IMAGE_NAME }}

    - name: Get file from artifacts
      uses: actions/download-artifact@v4.1.8
      with:
        name: ${{ env.IMAGE_NAME }}.txt

    - name: Output file content to log
      run: cat ${{ env.IMAGE_NAME }}.txt

    - name: Test
      run: echo "Integration tests are running on ${{ github.run_id }} for ${{ github.repository }} with image ${{ github.event.inputs.docker_image_name }}"