name: Integration Test Workflow

on:
  workflow_call:
    inputs:
      docker_image_name:
        description: 'Name of the Docker image'
        required: true
        type: string

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Test
      run: echo "Integration tests are running on ${{ github.run_id }} for ${{ github.repository }} with image ${{ github.event.inputs.docker_image_name }}"